-- =============================================================================
-- 043 - Student exam file library
-- Dynamic data source for "Kho đề thi Tiếng Anh" in MV Klass.
-- Upload files to Supabase Storage (or any public/signed URL source), then add
-- rows here. The web app reads published rows without redeploying.
-- =============================================================================

create table if not exists public.exam_files (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  level text not null check (level in ('entrance_10', 'university')),
  subject text not null default 'english' check (subject = 'english'),
  year integer,
  province text,
  category text not null default 'exam' check (category in ('exam', 'answer', 'audio', 'topic')),
  file_url text,
  answer_url text,
  audio_url text,
  description text,
  download_count integer not null default 0 check (download_count >= 0),
  created_at timestamptz not null default now(),
  is_published boolean not null default false
);

create index if not exists exam_files_published_idx
  on public.exam_files (is_published, subject, level, category, year desc, created_at desc);

comment on table public.exam_files is
  'Exam file library for student portal. Publish/unpublish rows without redeploying the web app.';

comment on column public.exam_files.file_url is
  'Main exam/topic file URL. Use a public Supabase Storage URL or a short-lived signed URL generated by admin tooling.';

-- Example row after uploading files to Storage > exam-files:
-- insert into public.exam_files
--   (title, level, subject, year, province, category, file_url, answer_url, audio_url, description, is_published)
-- values
--   ('Đề thi vào 10 Tiếng Anh Hà Nội 2025', 'entrance_10', 'english', 2025, 'Hà Nội', 'exam',
--    'https://<project-ref>.supabase.co/storage/v1/object/public/exam-files/vao-10/ha-noi-2025.pdf',
--    'https://<project-ref>.supabase.co/storage/v1/object/public/exam-files/vao-10/ha-noi-2025-dap-an.pdf',
--    null,
--    'Đề luyện cấu trúc thi vào 10, phù hợp làm trong 60 phút.',
--    true);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'exam-files',
  'exam-files',
  true,
  52428800,
  array[
    'application/pdf',
    'image/png',
    'image/jpeg',
    'audio/mpeg',
    'audio/mp4',
    'audio/wav',
    'audio/ogg',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
  ]
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

alter table public.exam_files enable row level security;

drop policy if exists "exam_files_read_published" on public.exam_files;
create policy "exam_files_read_published"
on public.exam_files
for select
to authenticated
using (is_published = true);

drop policy if exists "exam_files_admin_teacher_all" on public.exam_files;
create policy "exam_files_admin_teacher_all"
on public.exam_files
for all
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role in ('admin', 'teacher')
  )
)
with check (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role in ('admin', 'teacher')
  )
);

create or replace function public.increment_exam_download_count(p_exam_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.exam_files
  set download_count = coalesce(download_count, 0) + 1
  where id = p_exam_id
    and is_published = true;
end;
$$;

grant select on public.exam_files to authenticated;
grant execute on function public.increment_exam_download_count(uuid) to authenticated;

drop policy if exists "exam_files_storage_read" on storage.objects;
create policy "exam_files_storage_read"
on storage.objects
for select
to authenticated
using (bucket_id = 'exam-files');

drop policy if exists "exam_files_storage_admin_teacher_insert" on storage.objects;
create policy "exam_files_storage_admin_teacher_insert"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'exam-files'
  and exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role in ('admin', 'teacher')
  )
);

drop policy if exists "exam_files_storage_admin_teacher_update" on storage.objects;
create policy "exam_files_storage_admin_teacher_update"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'exam-files'
  and exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role in ('admin', 'teacher')
  )
)
with check (
  bucket_id = 'exam-files'
  and exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role in ('admin', 'teacher')
  )
);

drop policy if exists "exam_files_storage_admin_teacher_delete" on storage.objects;
create policy "exam_files_storage_admin_teacher_delete"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'exam-files'
  and exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role in ('admin', 'teacher')
  )
);

notify pgrst, 'reload schema';
